export const districts = [
  { label: 'Центральный административный округ', value: 'CAO' },
  { label: 'Северный административный округ', value: 'SAO' },
  { label: 'Северо-Восточный административный округ', value: 'SVAO' },
  { label: 'Восточный административный округ', value: 'VAO' },
  { label: 'Юго-Восточный административный округ', value: 'YuVAO' },
  { label: 'Южный административный округ', value: 'YuAO' },
  { label: 'Юго-Западный административный округ', value: 'YuZAO' },
  { label: 'Западный административный округ', value: 'ZAO' },
  { label: 'Северо-Западный административный округ', value: 'SZAO' },
  { label: 'Зеленоградский административный округ', value: 'ZelAO' },
  { label: 'Новомосковский административный округ', value: 'NAO' },
  { label: 'Троицкий административный округ', value: 'TAO' },
];

export const areas = [
  // ЦАО
  { label: 'Арбат', value: 'CAO-Arbat', district: 'CAO' },
  { label: 'Басманный', value: 'CAO-Basmanny', district: 'CAO' },
  { label: 'Замоскворечье', value: 'CAO-Zamoskvorechye', district: 'CAO' },
  { label: 'Красносельский', value: 'CAO-Krasnoselsky', district: 'CAO' },
  { label: 'Мещанский', value: 'CAO-Meshchansky', district: 'CAO' },
  { label: 'Пресненский', value: 'CAO-Presnensky', district: 'CAO' },
  { label: 'Таганский', value: 'CAO-Tagansky', district: 'CAO' },
  { label: 'Тверской', value: 'CAO-Tverskoy', district: 'CAO' },
  { label: 'Хамовники', value: 'CAO-Khamovniki', district: 'CAO' },
  { label: 'Якиманка', value: 'CAO-Yakimanka', district: 'CAO' },

  // САО
  { label: 'Аэропорт', value: 'SAO-Aeroport', district: 'SAO' },
  { label: 'Беговой', value: 'SAO-Begovoy', district: 'SAO' },
  { label: 'Бескудниковский', value: 'SAO-Beskudnikovsky', district: 'SAO' },
  { label: 'Войковский', value: 'SAO-Voykovsky', district: 'SAO' },
  { label: 'Головинский', value: 'SAO-Golovinsky', district: 'SAO' },
  { label: 'Дмитровский', value: 'SAO-Dmitrovsky', district: 'SAO' },
  { label: 'Коптево', value: 'SAO-Koptevo', district: 'SAO' },
  { label: 'Левобережный', value: 'SAO-Levoberezhny', district: 'SAO' },
  { label: 'Савёловский', value: 'SAO-Savyolovsky', district: 'SAO' },
  { label: 'Сокол', value: 'SAO-Sokol', district: 'SAO' },
  { label: 'Тимирязевский', value: 'SAO-Timiryazevsky', district: 'SAO' },
  { label: 'Ховрино', value: 'SAO-Khovrino', district: 'SAO' },

  // СВАО
  { label: 'Алексеевский', value: 'SVAO-Alekseevsky', district: 'SVAO' },
  { label: 'Алтуфьевский', value: 'SVAO-Altufyevsky', district: 'SVAO' },
  { label: 'Бабушкинский', value: 'SVAO-Babushkinsky', district: 'SVAO' },
  { label: 'Бибирево', value: 'SVAO-Bibirevo', district: 'SVAO' },
  { label: 'Бутырский', value: 'SVAO-Butyrsky', district: 'SVAO' },
  { label: 'Лианозово', value: 'SVAO-Lianozovo', district: 'SVAO' },
  { label: 'Марфино', value: 'SVAO-Marfino', district: 'SVAO' },
  { label: 'Марьина Роща', value: 'SVAO-Maryina-Roshcha', district: 'SVAO' },
  { label: 'Останкинский', value: 'SVAO-Ostankinsky', district: 'SVAO' },
  { label: 'Ростокино', value: 'SVAO-Rostokino', district: 'SVAO' },
  { label: 'Свиблово', value: 'SVAO-Sviblovo', district: 'SVAO' },
  { label: 'Северное Медведково', value: 'SVAO-Severnoe-Medvedkovo', district: 'SVAO' },
  { label: 'Южное Медведково', value: 'SVAO-Yuzhnoe-Medvedkovo', district: 'SVAO' },
  { label: 'Ярославский', value: 'SVAO-Yaroslavsky', district: 'SVAO' },

  // ВАО
  { label: 'Богородское', value: 'VAO-Bogorodskoe', district: 'VAO' },
  { label: 'Вешняки', value: 'VAO-Veshnyaki', district: 'VAO' },
  { label: 'Гольяново', value: 'VAO-Golyanovo', district: 'VAO' },
  { label: 'Измайлово', value: 'VAO-Izmailovo', district: 'VAO' },
  { label: 'Косино-Ухтомский', value: 'VAO-Kosino-Ukhtomsky', district: 'VAO' },
  { label: 'Новогиреево', value: 'VAO-Novogireevo', district: 'VAO' },
  { label: 'Новокосино', value: 'VAO-Novokosino', district: 'VAO' },
  { label: 'Перово', value: 'VAO-Perovo', district: 'VAO' },
  { label: 'Преображенское', value: 'VAO-Preobrazhenskoe', district: 'VAO' },
  { label: 'Соколиная Гора', value: 'VAO-Sokolinaya-Gora', district: 'VAO' },

  // ЮВАО
  { label: 'Выхино-Жулебино', value: 'YuVAO-Vykhino-Zhulebino', district: 'YuVAO' },
  { label: 'Капотня', value: 'YuVAO-Kapotnya', district: 'YuVAO' },
  { label: 'Кузьминки', value: 'YuVAO-Kuzminki', district: 'YuVAO' },
  { label: 'Лефортово', value: 'YuVAO-Lefortovo', district: 'YuVAO' },
  { label: 'Люблино', value: 'YuVAO-Lyublino', district: 'YuVAO' },
  { label: 'Марьино', value: 'YuVAO-Maryino', district: 'YuVAO' },
  { label: 'Некрасовка', value: 'YuVAO-Nekrasovka', district: 'YuVAO' },
  { label: 'Печатники', value: 'YuVAO-Pechatniki', district: 'YuVAO' },
  { label: 'Рязанский', value: 'YuVAO-Ryazansky', district: 'YuVAO' },
  { label: 'Текстильщики', value: 'YuVAO-Tekstilshchiki', district: 'YuVAO' },

  // ЮАО
  { label: 'Бирюлёво Восточное', value: 'YuAO-Biryulevo-East', district: 'YuAO' },
  { label: 'Бирюлёво Западное', value: 'YuAO-Biryulevo-West', district: 'YuAO' },
  { label: 'Братеево', value: 'YuAO-Brateevo', district: 'YuAO' },
  { label: 'Даниловский', value: 'YuAO-Danilovsky', district: 'YuAO' },
  { label: 'Зябликово', value: 'YuAO-Zyablikovo', district: 'YuAO' },
  { label: 'Москворечье-Сабурово', value: 'YuAO-Moskvorechye-Saburovo', district: 'YuAO' },
  { label: 'Нагатино-Садовники', value: 'YuAO-Nagatino-Sadovniki', district: 'YuAO' },
  { label: 'Нагатинский Затон', value: 'YuAO-Nagatinsky-Zaton', district: 'YuAO' },
  {
    label: 'Орехово-Борисово Северное',
    value: 'YuAO-Orekhovo-Borisovo-North',
    district: 'YuAO',
  },
  { label: 'Орехово-Борисово Южное', value: 'YuAO-Orekhovo-Borisovo-South', district: 'YuAO' },
  { label: 'Царицыно', value: 'YuAO-Tsaritsyno', district: 'YuAO' },
  { label: 'Чертаново Северное', value: 'YuAO-Chertanovo-North', district: 'YuAO' },
  { label: 'Чертаново Центральное', value: 'YuAO-Chertanovo-Center', district: 'YuAO' },
  { label: 'Чертаново Южное', value: 'YuAO-Chertanovo-South', district: 'YuAO' },

  // ЮЗАО
  { label: 'Академический', value: 'YuZAO-Akademichesky', district: 'YuZAO' },
  { label: 'Гагаринский', value: 'YuZAO-Gagarinsky', district: 'YuZAO' },
  { label: 'Зюзино', value: 'YuZAO-Zyuzino', district: 'YuZAO' },
  { label: 'Коньково', value: 'YuZAO-Konkovo', district: 'YuZAO' },
  { label: 'Котловка', value: 'YuZAO-Kotlovka', district: 'YuZAO' },
  { label: 'Ломоносовский', value: 'YuZAO-Lomonosovsky', district: 'YuZAO' },
  { label: 'Обручевский', value: 'YuZAO-Obruchevsky', district: 'YuZAO' },
  { label: 'Северное Бутово', value: 'YuZAO-Severnoe-Butovo', district: 'YuZAO' },
  { label: 'Южное Бутово', value: 'YuZAO-Yuzhnoe-Butovo', district: 'YuZAO' },
  { label: 'Ясенево', value: 'YuZAO-Yasenevo', district: 'YuZAO' },

  // ЗАО
  { label: 'Дорогомилово', value: 'ZAO-Dorogomilovo', district: 'ZAO' },
  { label: 'Крылатское', value: 'ZAO-Krylatskoye', district: 'ZAO' },
  { label: 'Кунцево', value: 'ZAO-Kuntsevo', district: 'ZAO' },
  { label: 'Можайский', value: 'ZAO-Mozhaysky', district: 'ZAO' },
  { label: 'Ново-Переделкино', value: 'ZAO-Novo-Peredelkino', district: 'ZAO' },
  { label: 'Очаково-Матвеевское', value: 'ZAO-Ochakovo-Matveevskoe', district: 'ZAO' },
  { label: 'Проспект Вернадского', value: 'ZAO-Prospekt-Vernadskogo', district: 'ZAO' },
  { label: 'Раменки', value: 'ZAO-Ramenki', district: 'ZAO' },
  { label: 'Солнцево', value: 'ZAO-Solntsevo', district: 'ZAO' },
  { label: 'Фили-Давыдково', value: 'ZAO-Fili-Davydkovo', district: 'ZAO' },

  // СЗАО
  { label: 'Куркино', value: 'SZAO-Kurkino', district: 'SZAO' },
  { label: 'Митино', value: 'SZAO-Mitino', district: 'SZAO' },
  { label: 'Покровское-Стрешнево', value: 'SZAO-Pokrovskoe-Streshnevo', district: 'SZAO' },
  { label: 'Северное Тушино', value: 'SZAO-Severnoe-Tushino', district: 'SZAO' },
  { label: 'Южное Тушино', value: 'SZAO-Yuzhnoe-Tushino', district: 'SZAO' },
  { label: 'Строгино', value: 'SZAO-Strogino', district: 'SZAO' },
  { label: 'Хорошёво-Мнёвники', value: 'SZAO-Khoroshevo-Mnevniki', district: 'SZAO' },
  { label: 'Щукино', value: 'SZAO-Shchukino', district: 'SZAO' },

  // Зеленоград
  { label: 'Матушкино', value: 'ZelAO-Matushkino', district: 'ZelAO' },
  { label: 'Савёлки', value: 'ZelAO-Savyolki', district: 'ZelAO' },
  { label: 'Старое Крюково', value: 'ZelAO-Staroe-Kryukovo', district: 'ZelAO' },
  { label: 'Силино', value: 'ZelAO-Silino', district: 'ZelAO' },
  { label: 'Крюково', value: 'ZelAO-Kryukovo', district: 'ZelAO' },

  // НАО
  { label: 'Московский', value: 'NAO-Moskovsky', district: 'NAO' },
  { label: 'Внуковское', value: 'NAO-Vnukovskoe', district: 'NAO' },
  { label: 'Сосенское', value: 'NAO-Sosenskoe', district: 'NAO' },
  { label: 'Десёновское', value: 'NAO-Desyonovskoe', district: 'NAO' },
  { label: 'Филимонковское', value: 'NAO-Filimonkovskoe', district: 'NAO' },

  // ТАО
  { label: 'Троицк', value: 'TAO-Troitsk', district: 'TAO' },
  { label: 'Щаповское', value: 'TAO-Shchapovskoe', district: 'TAO' },
  { label: 'Краснопахорское', value: 'TAO-Krasnopakhorskoe', district: 'TAO' },
  { label: 'Вороновское', value: 'TAO-Voronovskoe', district: 'TAO' },
  { label: 'Роговское', value: 'TAO-Rogovskoe', district: 'TAO' },
];
